name: my-python-project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Flask and Gunicorn
        run: |
          pip install flask
          pip install gunicorn

      - name: Build and Test
        run: python -m unittest discover

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/my-python-project
            git pull origin main

            # Restart Gunicorn
            systemctl restart gunicorn.service

            # Reload Nginx to pick up changes in the Nginx config
            systemctl reload nginx.service
